import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { TRPCReactProvider } from "~/trpc/react";
import { Sora, Space_Grotesk } from "next/font/google";

const grotesk = Space_Grotesk({
  weight: ["700"],
  subsets: ["latin"],
  variable: "--font-grotesk",
});

const sora = Sora({
  weight: ["600"],
  subsets: ["latin"],
  variable: "--font-sora",
});

export const metadata: Metadata = {
  title: "GithubAI",
  description: "Generated by Gemini",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${sora.variable} ${grotesk.variable}`}>
        <body>
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
           
          </SignedIn>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
