import "~/styles/globals.css";

import { type Metadata } from "next";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { TRPCReactProvider } from "~/trpc/react";
import { Sora, Space_Grotesk } from "next/font/google";
import { Toast } from "@radix-ui/react-toast";
import { Toaster } from "sonner";

const grotesk = Space_Grotesk({
  weight: ["700"],
  subsets: ["latin"],
  variable: "--font-grotesk",
});

const sora = Sora({
  weight: ["600"],
  subsets: ["latin"],
  variable: "--font-sora",
});

export const metadata: Metadata = {
  title: "GithubAI",
  description: "Generated by Gemini",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${sora.variable} ${grotesk.variable}`}>
        <body>
          <TRPCReactProvider>{children}</TRPCReactProvider>
          <Toaster/>
        </body>
      </html>
    </ClerkProvider>
  );
}
